package constants

type Currency struct {
	Name string
	Code string
}

var DefaultCurrency = Currency{Name: "US Dollar", Code: "USD"}

var CurrencyList = [...]Currency{
	{Name: "Afghan Afghani", Code: "AFA"},
	{Name: "Albanian Lek", Code: "ALL"},
	{Name: "Algerian Dinar", Code: "DZD"},
	{Name: "Angolan Kwanza", Code: "AOA"},
	{Name: "Argentine Peso", Code: "ARS"},
	{Name: "Armenian Dram", Code: "AMD"},
	{Name: "Aruban Florin", Code: "AWG"},
	{Name: "Australian Dollar", Code: "AUD"},
	{Name: "Azerbaijani Manat", Code: "AZN"},
	{Name: "Bahamian Dollar", Code: "BSD"},
	{Name: "Bahraini Dinar", Code: "BHD"},
	{Name: "Bangladeshi Taka", Code: "BDT"},
	{Name: "Barbadian Dollar", Code: "BBD"},
	{Name: "Belarusian Ruble", Code: "BYR"},
	{Name: "Belgian Franc", Code: "BEF"},
	{Name: "Belize Dollar", Code: "BZD"},
	{Name: "Bermudan Dollar", Code: "BMD"},
	{Name: "Bhutanese Ngultrum", Code: "BTN"},
	{Name: "Bitcoin", Code: "BTC"},
	{Name: "Bolivian Boliviano", Code: "BOB"},
	{Name: "Bosnia-Herzegovina Convertible Mark", Code: "BAM"},
	{Name: "Botswanan Pula", Code: "BWP"},
	{Name: "Brazilian Real", Code: "BRL"},
	{Name: "British Pound Sterling", Code: "GBP"},
	{Name: "Brunei Dollar", Code: "BND"},
	{Name: "Bulgarian Lev", Code: "BGN"},
	{Name: "Burundian Franc", Code: "BIF"},
	{Name: "Cambodian Riel", Code: "KHR"},
	{Name: "Canadian Dollar", Code: "CAD"},
	{Name: "Cape Verdean Escudo", Code: "CVE"},
	{Name: "Cayman Islands Dollar", Code: "KYD"},
	{Name: "CFA Franc BCEAO", Code: "XOF"},
	{Name: "CFA Franc BEAC", Code: "XAF"},
	{Name: "CFP Franc", Code: "XPF"},
	{Name: "Chilean Peso", Code: "CLP"},
	{Name: "Chilean Unit of Account", Code: "CLF"},
	{Name: "Chinese Yuan", Code: "CNY"},
	{Name: "Colombian Peso", Code: "COP"},
	{Name: "Comorian Franc", Code: "KMF"},
	{Name: "Congolese Franc", Code: "CDF"},
	{Name: "Costa Rican Colón", Code: "CRC"},
	{Name: "Croatian Kuna", Code: "HRK"},
	{Name: "Cuban Convertible Peso", Code: "CUC"},
	{Name: "Czech Republic Koruna", Code: "CZK"},
	{Name: "Danish Krone", Code: "DKK"},
	{Name: "Djiboutian Franc", Code: "DJF"},
	{Name: "Dominican Peso", Code: "DOP"},
	{Name: "East Caribbean Dollar", Code: "XCD"},
	{Name: "Egyptian Pound", Code: "EGP"},
	{Name: "Eritrean Nakfa", Code: "ERN"},
	{Name: "Estonian Kroon", Code: "EEK"},
	{Name: "Ethiopian Birr", Code: "ETB"},
	{Name: "Euro", Code: "EUR"},
	{Name: "Falkland Islands Pound", Code: "FKP"},
	{Name: "Fijian Dollar", Code: "FJD"},
	{Name: "Gambian Dalasi", Code: "GMD"},
	{Name: "Georgian Lari", Code: "GEL"},
	{Name: "German Mark", Code: "DEM"},
	{Name: "Ghanaian Cedi", Code: "GHS"},
	{Name: "Gibraltar Pound", Code: "GIP"},
	{Name: "Greek Drachma", Code: "GRD"},
	{Name: "Guatemalan Quetzal", Code: "GTQ"},
	{Name: "Guinean Franc", Code: "GNF"},
	{Name: "Guyanaese Dollar", Code: "GYD"},
	{Name: "Haitian Gourde", Code: "HTG"},
	{Name: "Honduran Lempira", Code: "HNL"},
	{Name: "Hong Kong Dollar", Code: "HKD"},
	{Name: "Hungarian Forint", Code: "HUF"},
	{Name: "Icelandic Króna", Code: "ISK"},
	{Name: "Indian Rupee", Code: "INR"},
	{Name: "Indonesian Rupiah", Code: "IDR"},
	{Name: "Iranian Rial", Code: "IRR"},
	{Name: "Iraqi Dinar", Code: "IQD"},
	{Name: "Israeli New Sheqel", Code: "ILS"},
	{Name: "Italian Lira", Code: "ITL"},
	{Name: "Jamaican Dollar", Code: "JMD"},
	{Name: "Japanese Yen", Code: "JPY"},
	{Name: "Jordanian Dinar", Code: "JOD"},
	{Name: "Kazakhstani Tenge", Code: "KZT"},
	{Name: "Kenyan Shilling", Code: "KES"},
	{Name: "Kuwaiti Dinar", Code: "KWD"},
	{Name: "Kyrgystani Som", Code: "KGS"},
	{Name: "Laotian Kip", Code: "LAK"},
	{Name: "Latvian Lats", Code: "LVL"},
	{Name: "Lebanese Pound", Code: "LBP"},
	{Name: "Lesotho Loti", Code: "LSL"},
	{Name: "Liberian Dollar", Code: "LRD"},
	{Name: "Libyan Dinar", Code: "LYD"},
	{Name: "Litecoin", Code: "LTC"},
	{Name: "Lithuanian Litas", Code: "LTL"},
	{Name: "Macanese Pataca", Code: "MOP"},
	{Name: "Macedonian Denar", Code: "MKD"},
	{Name: "Malagasy Ariary", Code: "MGA"},
	{Name: "Malawian Kwacha", Code: "MWK"},
	{Name: "Malaysian Ringgit", Code: "MYR"},
	{Name: "Maldivian Rufiyaa", Code: "MVR"},
	{Name: "Mauritanian Ouguiya", Code: "MRO"},
	{Name: "Mauritian Rupee", Code: "MUR"},
	{Name: "Mexican Peso", Code: "MXN"},
	{Name: "Moldovan Leu", Code: "MDL"},
	{Name: "Mongolian Tugrik", Code: "MNT"},
	{Name: "Moroccan Dirham", Code: "MAD"},
	{Name: "Mozambican Metical", Code: "MZM"},
	{Name: "Myanmar Kyat", Code: "MMK"},
	{Name: "Namibian Dollar", Code: "NAD"},
	{Name: "Nepalese Rupee", Code: "NPR"},
	{Name: "Netherlands Antillean Guilder", Code: "ANG"},
	{Name: "New Taiwan Dollar", Code: "TWD"},
	{Name: "New Zealand Dollar", Code: "NZD"},
	{Name: "Nicaraguan Córdoba", Code: "NIO"},
	{Name: "Nigerian Naira", Code: "NGN"},
	{Name: "North Korean Won", Code: "KPW"},
	{Name: "Norwegian Krone", Code: "NOK"},
	{Name: "Omani Rial", Code: "OMR"},
	{Name: "Pakistani Rupee", Code: "PKR"},
	{Name: "Panamanian Balboa", Code: "PAB"},
	{Name: "Papua New Guinean Kina", Code: "PGK"},
	{Name: "Paraguayan Guarani", Code: "PYG"},
	{Name: "Peruvian Nuevo Sol", Code: "PEN"},
	{Name: "Philippine Peso", Code: "PHP"},
	{Name: "Polish Zloty", Code: "PLN"},
	{Name: "Qatari Rial", Code: "QAR"},
	{Name: "Romanian Leu", Code: "RON"},
	{Name: "Russian Ruble", Code: "RUB"},
	{Name: "Rwandan Franc", Code: "RWF"},
	{Name: "Salvadoran Colón", Code: "SVC"},
	{Name: "Samoan Tala", Code: "WST"},
	{Name: "São Tomé and Príncipe Dobra", Code: "STD"},
	{Name: "Saudi Riyal", Code: "SAR"},
	{Name: "Serbian Dinar", Code: "RSD"},
	{Name: "Seychellois Rupee", Code: "SCR"},
	{Name: "Sierra Leonean Leone", Code: "SLL"},
	{Name: "Singapore Dollar", Code: "SGD"},
	{Name: "Slovak Koruna", Code: "SKK"},
	{Name: "Solomon Islands Dollar", Code: "SBD"},
	{Name: "Somali Shilling", Code: "SOS"},
	{Name: "South African Rand", Code: "ZAR"},
	{Name: "South Korean Won", Code: "KRW"},
	{Name: "South Sudanese Pound", Code: "SSP"},
	{Name: "Special Drawing Rights", Code: "XDR"},
	{Name: "Sri Lankan Rupee", Code: "LKR"},
	{Name: "St. Helena Pound", Code: "SHP"},
	{Name: "Sudanese Pound", Code: "SDG"},
	{Name: "Surinamese Dollar", Code: "SRD"},
	{Name: "Swazi Lilangeni", Code: "SZL"},
	{Name: "Swedish Krona", Code: "SEK"},
	{Name: "Swiss Franc", Code: "CHF"},
	{Name: "Syrian Pound", Code: "SYP"},
	{Name: "Tajikistani Somoni", Code: "TJS"},
	{Name: "Tanzanian Shilling", Code: "TZS"},
	{Name: "Thai Baht", Code: "THB"},
	{Name: "Tongan Pa'anga", Code: "TOP"},
	{Name: "Trinidad & Tobago Dollar", Code: "TTD"},
	{Name: "Tunisian Dinar", Code: "TND"},
	{Name: "Turkish Lira", Code: "TRY"},
	{Name: "Turkmenistani Manat", Code: "TMT"},
	{Name: "Ugandan Shilling", Code: "UGX"},
	{Name: "Ukrainian Hryvnia", Code: "UAH"},
	{Name: "United Arab Emirates Dirham", Code: "AED"},
	{Name: "Uruguayan Peso", Code: "UYU"},
	{Name: "US Dollar", Code: "USD"},
	{Name: "Uzbekistan Som", Code: "UZS"},
	{Name: "Vanuatu Vatu", Code: "VUV"},
	{Name: "Venezuelan BolÃvar", Code: "VEF"},
	{Name: "Vietnamese Dong", Code: "VND"},
	{Name: "Yemeni Rial", Code: "YER"},
	{Name: "Zambian Kwacha", Code: "ZMK"},
	{Name: "Zimbabwean dollar", Code: "ZWL"}}
