// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateAccountHolders implements pgx.CopyFromSource.
type iteratorForCreateAccountHolders struct {
	rows                 []CreateAccountHoldersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAccountHolders) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAccountHolders) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccID,
		r.rows[0].UserID,
	}, nil
}

func (r iteratorForCreateAccountHolders) Err() error {
	return nil
}

func (q *Queries) CreateAccountHolders(ctx context.Context, arg []CreateAccountHoldersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account_holders"}, []string{"acc_id", "user_id"}, &iteratorForCreateAccountHolders{rows: arg})
}
